name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - name: Set Git credentials
        run: |
          git config user.name "p0uryRokn"
          git config user.email "pouryrokn@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/p0uryRokn/semantic-release.git

      - name: Run semantic-release
        run: npx semantic-release
